import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createServer, type Server } from "node:http";

const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), "axiom-github-review-test-"));
const submittedAt = new Date().toISOString();
const reviewJobId = "job_github_review";
const rollbackJobId = "job_github_rollback";

process.env.NODE_ENV = "production";
process.env.AXIOM_DISABLE_AUTOSTART = "true";
process.env.ENABLE_DEV_LOGIN = "true";
process.env.DEV_LOGIN_TOKEN = "github-review-dev-login-token";
process.env.ENABLE_GITHUB_APP_REVIEW_ACTIONS = "true";
process.env.ENABLE_GITHUB_APP_ROLLBACK_ACTIONS = "true";
process.env.HERMES_MEMORY_EVICTION_WEBHOOK_TOKEN = "hermes-evict-token";
delete process.env.ENABLE_LOCAL_REVIEW_ACTIONS;
delete process.env.ENABLE_LOCAL_WORKFLOW_RUNNER;
process.env.GEMINI_API_KEY = "MY_GEMINI_API_KEY";
process.env.DATA_DIR = dataDir;
process.env.STORAGE_PROVIDER = "json";
process.env.APP_URL = "http://127.0.0.1";
process.env.SESSION_SECRET = "github-review-test-session-secret";
process.env.INTEGRATION_ENCRYPTION_KEY = "github-review-test-integration-secret";
process.env.DEFAULT_TARGET_REPOSITORY = "acme/widgets";
delete process.env.DATABASE_URL;

function storedReviewJob() {
  return {
    id: reviewJobId,
    executionId: `exec_${reviewJobId}`,
    hermesSessionId: `hermes_${reviewJobId}`,
    taskName: "Merge GitHub App PR",
    scopeDescription: "Merge GitHub App PR",
    currentPhase: "PULL_REQUEST_OPEN",
    gitBranch: "feature/hermes-real-branch",
    targetRepository: "acme/widgets",
    status: "REVIEW_READY",
    phaseIndex: 6,
    runningText: "Pending manager review",
    terminalStatus: "PR_DRAFT",
    activeIterationIndex: 2,
    assignedTo: "Manager Review",
    submittedAt,
    queuedAt: submittedAt,
    queueState: "COMPLETED",
    createdByUserId: "usr_seed",
    developerRole: "Developer",
    qaRole: "QA",
    estimate: {
      estimatedCost: 0.01,
      inputTokens: 100,
      outputTokens: 200,
      computeMs: 1000,
      isComplex: false,
    },
    pullRequest: {
      number: 42,
      url: "https://github.example/acme/widgets/pull/42",
      state: "open",
      draft: false,
      title: "feat: autonomous sandbox proof",
      body: "Proof generated by the production GitHub App path.",
      headRef: "feature/hermes-real-branch",
      headSha: "1234567890abcdef1234567890abcdef12345678",
      baseRef: "main",
      baseSha: "abcdef1234567890abcdef1234567890abcdef12",
      merged: false,
    },
    logs: ["seeded github review fixture"],
  };
}

function storedRollbackJob() {
  return {
    id: rollbackJobId,
    executionId: `exec_${rollbackJobId}`,
    hermesSessionId: `hermes_${rollbackJobId}`,
    taskName: "Rollback GitHub App PR",
    scopeDescription: "Rollback GitHub App PR",
    currentPhase: "PULL_REQUEST_OPEN",
    gitBranch: "feature/hermes-rollback-branch",
    targetRepository: "acme/widgets",
    status: "REVIEW_READY",
    phaseIndex: 6,
    runningText: "Pending manager review",
    terminalStatus: "PR_DRAFT",
    activeIterationIndex: 2,
    assignedTo: "Manager Review",
    submittedAt,
    queuedAt: submittedAt,
    queueState: "COMPLETED",
    createdByUserId: "usr_seed",
    developerRole: "Developer",
    qaRole: "QA",
    estimate: {
      estimatedCost: 0.01,
      inputTokens: 100,
      outputTokens: 200,
      computeMs: 1000,
      isComplex: false,
    },
    pullRequest: {
      number: 43,
      url: "https://github.example/acme/widgets/pull/43",
      state: "open",
      draft: false,
      title: "feat: rollback candidate",
      body: "Candidate generated by the production GitHub App path.",
      headRef: "feature/hermes-rollback-branch",
      headSha: "fedcba0987654321fedcba0987654321fedcba09",
      baseRef: "main",
      baseSha: "abcdef1234567890abcdef1234567890abcdef12",
      merged: false,
    },
    logs: ["seeded github rollback fixture"],
  };
}

await fs.mkdir(dataDir, { recursive: true });
await fs.writeFile(
  path.join(dataDir, "hermes-store.json"),
  JSON.stringify({
    users: [],
    sessions: [],
    oauthStates: [],
    inviteTokens: [],
    integrations: [],
    jobs: [storedReviewJob(), storedRollbackJob()],
  }, null, 2),
);

const githubApiRequests: Array<{ method: string; url: string; authorization?: string; body?: string }> = [];
const hermesEvictionRequests: Array<{ method: string; url: string; authorization?: string; body?: string }> = [];
const { privateKey: githubAppPrivateKey } = crypto.generateKeyPairSync("rsa", { modulusLength: 2048 });
const githubAppPrivateKeyPem = githubAppPrivateKey.export({ type: "pkcs8", format: "pem" }).toString();

const githubApiServer = createServer((req, res) => {
  const requestRecord = {
    method: req.method || "",
    url: req.url || "",
    authorization: req.headers.authorization,
    body: undefined as string | undefined,
  };
  githubApiRequests.push(requestRecord);

  if (req.method === "POST" && req.url === "/app/installations/67890/access_tokens") {
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({
      token: "ghs_do_not_return",
      expires_at: "2030-01-01T00:00:00Z",
      permissions: {
        contents: "write",
        pull_requests: "write",
      },
    }));
    return;
  }

  if (req.method === "GET" && req.url === "/repos/acme/widgets") {
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({
      full_name: "acme/widgets",
      default_branch: "main",
      private: true,
      permissions: {
        contents: true,
        pull: true,
        push: true,
      },
    }));
    return;
  }

  if (req.method === "GET" && req.url === "/repos/acme/widgets/git/ref/heads/main") {
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({
      ref: "refs/heads/main",
      object: {
        sha: "abcdef1234567890abcdef1234567890abcdef12",
        type: "commit",
      },
    }));
    return;
  }

  if (req.method === "GET" && req.url === "/repos/acme/widgets/git/ref/heads/feature%2Fhermes-rollback-branch") {
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({
      ref: "refs/heads/feature/hermes-rollback-branch",
      object: {
        sha: "rollbackbranch123",
        type: "commit",
      },
    }));
    return;
  }

  if (req.method === "DELETE" && req.url === "/repos/acme/widgets/git/refs/heads/feature%2Fhermes-rollback-branch") {
    const chunks: Buffer[] = [];
    req.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    req.on("end", () => {
      requestRecord.body = Buffer.concat(chunks).toString("utf8");
      res.statusCode = 204;
      res.end();
    });
    return;
  }

  if (req.method === "PUT" && req.url === "/repos/acme/widgets/pulls/42/merge") {
    const chunks: Buffer[] = [];
    req.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    req.on("end", () => {
      requestRecord.body = Buffer.concat(chunks).toString("utf8");
      res.setHeader("Content-Type", "application/json");
      res.end(JSON.stringify({
        sha: "merge123abc",
        merged: true,
        message: "Pull Request successfully merged",
      }));
    });
    return;
  }

  res.statusCode = 404;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify({ message: "not found" }));
});

const hermesEvictionServer = createServer((req, res) => {
  const requestRecord = {
    method: req.method || "",
    url: req.url || "",
    authorization: req.headers.authorization,
    body: undefined as string | undefined,
  };
  hermesEvictionRequests.push(requestRecord);

  if (req.method === "POST" && req.url === "/evict") {
    const chunks: Buffer[] = [];
    req.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    req.on("end", () => {
      requestRecord.body = Buffer.concat(chunks).toString("utf8");
      res.setHeader("Content-Type", "application/json");
      res.end(JSON.stringify({ evictionId: "evict_rollback_123" }));
    });
    return;
  }

  res.statusCode = 404;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify({ message: "not found" }));
});

await new Promise<void>((resolve, reject) => {
  githubApiServer.listen(0, "127.0.0.1");
  githubApiServer.once("listening", resolve);
  githubApiServer.once("error", reject);
});
const githubApiAddress = githubApiServer.address();
assert.ok(githubApiAddress && typeof githubApiAddress === "object");
process.env.GITHUB_API_BASE_URL = `http://127.0.0.1:${githubApiAddress.port}`;

await new Promise<void>((resolve, reject) => {
  hermesEvictionServer.listen(0, "127.0.0.1");
  hermesEvictionServer.once("listening", resolve);
  hermesEvictionServer.once("error", reject);
});
const hermesEvictionAddress = hermesEvictionServer.address();
assert.ok(hermesEvictionAddress && typeof hermesEvictionAddress === "object");
process.env.HERMES_MEMORY_EVICTION_WEBHOOK_URL = `http://127.0.0.1:${hermesEvictionAddress.port}/evict`;

const { startServer } = await import("../server.ts");

let server: Server;
let baseUrl = "";

async function readJson<T>(response: Response): Promise<T> {
  const text = await response.text();
  return JSON.parse(text) as T;
}

function cookieFrom(response: Response) {
  const cookie = response.headers.get("set-cookie")?.split(";")[0];
  assert.ok(cookie, "expected response to include a session cookie");
  return cookie;
}

test.before(async () => {
  server = await startServer({
    port: 0,
    host: "127.0.0.1",
    serveClient: false,
  });
  const address = server.address();
  assert.ok(address && typeof address === "object");
  baseUrl = `http://127.0.0.1:${address.port}`;
});

test.after(async () => {
  if (server) {
    await new Promise<void>((resolve, reject) => {
      server.close((error) => (error ? reject(error) : resolve()));
    });
  }
  await new Promise<void>((resolve, reject) => {
    githubApiServer.close((error) => (error ? reject(error) : resolve()));
  });
  await new Promise<void>((resolve, reject) => {
    hermesEvictionServer.close((error) => (error ? reject(error) : resolve()));
  });
  await fs.rm(dataDir, { recursive: true, force: true });
});

test("production review actions use GitHub App and Hermes adapters", async () => {
  let response = await fetch(`${baseUrl}/api/auth/dev-login`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Dev-Login-Token": process.env.DEV_LOGIN_TOKEN!,
    },
    body: JSON.stringify({
      email: "admin@github-review.test",
      fullName: "GitHub Review Admin",
    }),
  });
  const adminCookie = cookieFrom(response);
  const adminLogin = await readJson<{ csrfToken: string }>(response);
  assert.equal(response.status, 200);

  response = await fetch(`${baseUrl}/api/integrations`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Cookie: adminCookie,
      "X-CSRF-Token": adminLogin.csrfToken,
    },
    body: JSON.stringify({
      provider: "github_app",
      displayName: "GitHub App Review Test",
      secrets: {
        app_id: "12345",
        installation_id: "67890",
        private_key: githubAppPrivateKeyPem,
      },
    }),
  });
  assert.equal(response.status, 201);

  response = await fetch(`${baseUrl}/api/settings`, {
    headers: { Cookie: adminCookie },
  });
  const settings = await readJson<{
    runtime: {
      reviewActionProvider: string;
      reviewActionsEnabled: boolean;
      localReviewActionsEnabled: boolean;
      githubAppReviewActionsEnabled: boolean;
      rollbackActionProvider: string;
      rollbackActionsEnabled: boolean;
      githubAppRollbackActionsEnabled: boolean;
      hermesMemoryEvictionConfigured: boolean;
    };
  }>(response);
  assert.equal(response.status, 200);
  assert.equal(settings.runtime.reviewActionProvider, "github-app-adapter");
  assert.equal(settings.runtime.reviewActionsEnabled, true);
  assert.equal(settings.runtime.localReviewActionsEnabled, false);
  assert.equal(settings.runtime.githubAppReviewActionsEnabled, true);
  assert.equal(settings.runtime.rollbackActionProvider, "github-app-hermes-adapter");
  assert.equal(settings.runtime.rollbackActionsEnabled, true);
  assert.equal(settings.runtime.githubAppRollbackActionsEnabled, true);
  assert.equal(settings.runtime.hermesMemoryEvictionConfigured, true);

  response = await fetch(`${baseUrl}/api/jobs/${reviewJobId}/approve`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Cookie: adminCookie,
      "X-CSRF-Token": adminLogin.csrfToken,
    },
    body: JSON.stringify({
      mergeMethod: "squash",
      commitTitle: "feat: autonomous sandbox proof",
      commitMessage: "Verified through job approval.",
    }),
  });
  const approved = await readJson<{
    job: {
      status: string;
      currentPhase: string;
      pullRequest: {
        number: number;
        merged: boolean;
        mergeSha: string;
        state: string;
      };
      pipelineState: {
        logs: string[];
      };
    };
  }>(response);
  assert.equal(response.status, 200);
  assert.equal(approved.job.status, "COMPLETED");
  assert.equal(approved.job.currentPhase, "COMPLETED_MERGED");
  assert.equal(approved.job.pullRequest.number, 42);
  assert.equal(approved.job.pullRequest.merged, true);
  assert.equal(approved.job.pullRequest.mergeSha, "merge123abc");
  assert.equal(approved.job.pullRequest.state, "closed");
  assert.ok(approved.job.pipelineState.logs.some((line) => line.includes("merged via GitHub App")));

  assert.equal(githubApiRequests.at(-2)?.url, "/app/installations/67890/access_tokens");
  const mergeRequest = githubApiRequests.at(-1);
  assert.equal(mergeRequest?.method, "PUT");
  assert.equal(mergeRequest?.url, "/repos/acme/widgets/pulls/42/merge");
  assert.ok(mergeRequest?.authorization?.startsWith("Bearer ghs_do_not_return"));
  assert.deepEqual(JSON.parse(mergeRequest?.body || "{}"), {
    merge_method: "squash",
    commit_title: "feat: autonomous sandbox proof",
    commit_message: "Verified through job approval.",
    sha: "1234567890abcdef1234567890abcdef12345678",
  });

  response = await fetch(`${baseUrl}/api/jobs/${rollbackJobId}/rollback`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Cookie: adminCookie,
      "X-CSRF-Token": adminLogin.csrfToken,
    },
    body: JSON.stringify({}),
  });
  const rolledBack = await readJson<{
    job: {
      status: string;
      currentPhase: string;
      rollbackSnapshot: {
        branchDeleted: boolean;
        jobStateReverted: boolean;
        memoryEvicted: boolean;
      };
      pipelineState: {
        logs: string[];
      };
    };
  }>(response);
  assert.equal(response.status, 200);
  assert.equal(rolledBack.job.status, "ROLLED_BACK");
  assert.equal(rolledBack.job.currentPhase, "ROLLED_BACK");
  assert.equal(rolledBack.job.rollbackSnapshot.branchDeleted, true);
  assert.equal(rolledBack.job.rollbackSnapshot.jobStateReverted, true);
  assert.equal(rolledBack.job.rollbackSnapshot.memoryEvicted, true);
  assert.ok(rolledBack.job.pipelineState.logs.some((line) => line.includes("deleted via GitHub App")));
  assert.ok(rolledBack.job.pipelineState.logs.some((line) => line.includes("Agent memory context evicted")));
  assert.ok(rolledBack.job.pipelineState.logs.some((line) => line.includes("Eviction ID: evict_rollback_123")));

  assert.ok(githubApiRequests.some((request) => request.method === "GET" && request.url === "/repos/acme/widgets"));
  assert.ok(githubApiRequests.some((request) => request.method === "GET" && request.url === "/repos/acme/widgets/git/ref/heads/main"));
  assert.ok(githubApiRequests.some((request) => request.method === "GET" && request.url === "/repos/acme/widgets/git/ref/heads/feature%2Fhermes-rollback-branch"));
  const deleteRequest = githubApiRequests.find((request) => request.method === "DELETE" && request.url === "/repos/acme/widgets/git/refs/heads/feature%2Fhermes-rollback-branch");
  assert.ok(deleteRequest, "expected branch deletion request");
  assert.ok(deleteRequest.authorization?.startsWith("Bearer ghs_do_not_return"));

  assert.equal(hermesEvictionRequests.length, 1);
  const hermesRequest = hermesEvictionRequests[0];
  assert.equal(hermesRequest.authorization, "Bearer hermes-evict-token");
  const hermesPayload = JSON.parse(hermesRequest.body || "{}");
  assert.deepEqual(hermesPayload, {
    jobId: rollbackJobId,
    executionId: `exec_${rollbackJobId}`,
    hermesSessionId: `hermes_${rollbackJobId}`,
    gitBranch: "feature/hermes-rollback-branch",
    targetRepository: "acme/widgets",
    requestedByEmail: "admin@github-review.test",
    requestedAt: hermesPayload.requestedAt,
  });
  assert.ok(hermesPayload.requestedAt);
});
